version: 1

plane:
  width_mm: 300.0
  height_mm: 200.0
  mm_per_px: 0.5

logos:
  - name: "pecho"
    template_path: "templates/logo_pecho.png"
    position_mm: [150.0, 100.0]
    roi:
      width_mm: 50.0
      height_mm: 40.0
      margin_factor: 1.2
    angle_deg: 0.0

  - name: "manga_izq"
    template_path: "templates/logo_manga_izq.png"
    position_mm: [50.0, 60.0]
    roi:
      width_mm: 30.0
      height_mm: 25.0
      margin_factor: 1.3
    angle_deg: 0.0

  - name: "manga_der"
    template_path: "templates/logo_manga_der.png"
    position_mm: [250.0, 60.0]
    roi:
      width_mm: 30.0
      height_mm: 25.0
      margin_factor: 1.3
    angle_deg: 0.0

thresholds:
  position_tolerance_mm: 3.0
  angle_tolerance_deg: 5.0
  min_inliers: 15
  max_reproj_error: 3.0

features:
  feature_type: "ORB"
  nfeatures: 1500
  scale_factor: 1.2
  nlevels: 8

fallback:
  enabled: true
  scales: [0.8, 0.9, 1.0, 1.1, 1.2]
  angles: [-10, -5, 0, 5, 10]
  match_threshold: 0.7