version: 1

# Configuración para plancha real de 50cm x 60cm
plane:
  width_mm: 500.0    # 50 cm
  height_mm: 600.0   # 60 cm
  mm_per_px: 0.08467 # Obtenido de calibración real

# Logo configuration - ajustar según tu logo específico
logos:
  - name: "logo_pecho"
    template_path: "test_template.png"
    position_mm: [169.3, 203.2]  # Posición real del logo extraído
    roi:
      width_mm: 200.0   # ROI ajustado para nueva escala
      height_mm: 200.0
      margin_factor: 1.5  # Margen razonable
    angle_deg: 0.0

# Thresholds ajustados para testing real
thresholds:
  position_tolerance_mm: 20.0   # Máximo permitido
  angle_tolerance_deg: 30.0     # Muy tolerante
  min_inliers: 4                # Mínimo permitido
  max_reproj_error: 10.0        # Muy tolerante

# Features optimizados para logos reales
features:
  feature_type: "ORB"
  nfeatures: 2000               # Más features para mejor detección
  scale_factor: 1.2
  nlevels: 8

# Fallback más robusto para condiciones reales
fallback:
  enabled: true
  scales: [0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3]  # Rango más amplio
  angles: [-15, -10, -5, 0, 5, 10, 15]          # Más variaciones de ángulo
  match_threshold: 0.65         # Más permisivo para templates reales